<a href="https://colab.research.google.com/github/darshbaxi/Tensorflow-Practice/blob/main/Fundamental_tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [33]:
import tensorflow as tf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [34]:
matrix=tf.constant([[[1,2,3],[1,2,3]],[[4,5,6],[7,8,9]],[[8,9,7],[8,5,6]],[[8,9,7],[8,5,6]]])

In [35]:
matrix

<tf.Tensor: shape=(4, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [1, 2, 3]],

       [[4, 5, 6],
        [7, 8, 9]],

       [[8, 9, 7],
        [8, 5, 6]],

       [[8, 9, 7],
        [8, 5, 6]]], dtype=int32)>

In [36]:
matrix.ndim

3

In [37]:
a=np.array([[0],[1],[2]])
b=np.array([[0],[1],[2]])

In [38]:
print(np.hstack((a,b)));

[[0 0]
 [1 1]
 [2 2]]


In [39]:

df=pd.read_csv("50_Startups.csv")

In [65]:


df = df.sample(frac = 1) #### for suffling the data;

df

R&DSpend  Administration  MarketingSpend       State     Profit
11  100671.96        91790.61             NaN  California  144259.40
41   27892.92             NaN       164470.71     Florida   77798.83
8   120542.52       148718.95             NaN    New York  152211.77
37   44069.95        51283.14       197029.42  California   89949.14
32   63408.86       129219.61        46085.25  California   97427.84
18   91749.16       114175.79       294919.57     Florida  124266.90
43        NaN       127382.30        35534.17    New York   69758.98
46    1315.46       115816.21       297114.46     Florida   49490.75
10        NaN       110594.11       229160.95     Florida  146121.95
34   46426.07             NaN       210797.67  California   96712.80
28   66051.52       182645.56       118148.20     Florida  103282.38
20   76253.86       113867.30       298664.47  California  118474.03
4   142107.34        91391.77       366168.42     Florida  166187.94
19        NaN       153514.11             NaN    New York  122776.86
13   91992.39       135495.07       252664.93  California  134307.35
15  114523.61       122616.84       261776.23    New York  129917.04
23   67532.53       105751.03       304768.73     Florida  108733.99
36   28663.76       127056.21       201126.82     Florida   90708.19
35   46014.02        85047.44       205517.64    New York   96479.51
42   23640.93        96189.63       148001.11  California   71498.49
30   61994.48       115641.28        91131.24     Florida   99937.59
31   61136.38       152701.92             NaN    New York   97483.56
2   153441.51       101145.55       407934.54     Florida  191050.39
21   78389.47       153773.43       299737.29    New York  111313.02
12   93863.75       127320.38       249839.44     Florida  141585.52
24   77044.01        99281.34             NaN    New York  108552.04
5         NaN        99814.71       362861.36    New York  156991.12
0   165349.20       136897.80       471784.10    New York  192261.83
33        NaN       103057.49       214634.81     Florida   96778.92
25        NaN             NaN       137962.62  California  107404.34
47        NaN       135426.92             NaN  California   42559.73
14  119943.24       156547.42       256512.92     Florida  132602.65
22   73994.56       122782.75       303319.26     Florida  110352.25
16   78013.11             NaN       264346.06  California  126992.93
26   75328.87       144135.98       134050.07     Florida  105733.54
9   123334.88       108679.17       304981.62  California  149759.96
7   130298.13       145530.06       323876.68     Florida  155752.60
39   38558.51        82982.09             NaN  California   81005.76
27   72107.60       127864.55       353183.81    New York  105008.31
29   65605.48       153032.06       107138.38    New York  101004.64
1   162597.70       151377.59       443898.53  California  191792.06
45    1000.23       124153.04         1903.93    New York   64926.08
38   20229.59        65947.93       185265.10    New York   81229.06
40   28754.33       118546.05       172795.67  California   78239.91
48     542.05        51743.15             NaN    New York   35673.41
3   144372.41       118671.85       383199.62    New York  182901.99
44   22177.74       154806.14        28334.72  California   65200.33
49        NaN       116983.80        45173.06  California   14681.40
6   134615.46       147198.87       127716.82  California  156122.51
17   94657.16       145077.58       282574.31    New York  125370.37

In [41]:
x=df.iloc[:,:-1]

In [42]:
x.shape

(50, 4)

In [43]:
y=df.iloc[:,-1]
y

0     192261.83
1     191792.06
2     191050.39
3     182901.99
4     166187.94
5     156991.12
6     156122.51
7     155752.60
8     152211.77
9     149759.96
10    146121.95
11    144259.40
12    141585.52
13    134307.35
14    132602.65
15    129917.04
16    126992.93
17    125370.37
18    124266.90
19    122776.86
20    118474.03
21    111313.02
22    110352.25
23    108733.99
24    108552.04
25    107404.34
26    105733.54
27    105008.31
28    103282.38
29    101004.64
30     99937.59
31     97483.56
32     97427.84
33     96778.92
34     96712.80
35     96479.51
36     90708.19
37     89949.14
38     81229.06
39     81005.76
40     78239.91
41     77798.83
42     71498.49
43     69758.98
44     65200.33
45     64926.08
46     49490.75
47     42559.73
48     35673.41
49     14681.40
Name: Profit, dtype: float64

In [52]:
import math
x_train=math.floor(x.shape[0]*0.80)


In [60]:

x_tarin=x.iloc[:x_train,:]

In [61]:
x_tarin


R&DSpend  Administration  MarketingSpend       State
0   165349.20       136897.80       471784.10    New York
1   162597.70       151377.59       443898.53  California
2   153441.51       101145.55       407934.54     Florida
3   144372.41       118671.85       383199.62    New York
4   142107.34        91391.77       366168.42     Florida
5         NaN        99814.71       362861.36    New York
6   134615.46       147198.87       127716.82  California
7   130298.13       145530.06       323876.68     Florida
8   120542.52       148718.95             NaN    New York
9   123334.88       108679.17       304981.62  California
10        NaN       110594.11       229160.95     Florida
11  100671.96        91790.61             NaN  California
12   93863.75       127320.38       249839.44     Florida
13   91992.39       135495.07       252664.93  California
14  119943.24       156547.42       256512.92     Florida
15  114523.61       122616.84       261776.23    New York
16   78013.11             NaN       264346.06  California
17   94657.16       145077.58       282574.31    New York
18   91749.16       114175.79       294919.57     Florida
19        NaN       153514.11             NaN    New York
20   76253.86       113867.30       298664.47  California
21   78389.47       153773.43       299737.29    New York
22   73994.56       122782.75       303319.26     Florida
23   67532.53       105751.03       304768.73     Florida
24   77044.01        99281.34             NaN    New York
25        NaN             NaN       137962.62  California
26   75328.87       144135.98       134050.07     Florida
27   72107.60       127864.55       353183.81    New York
28   66051.52       182645.56       118148.20     Florida
29   65605.48       153032.06       107138.38    New York
30   61994.48       115641.28        91131.24     Florida
31   61136.38       152701.92             NaN    New York
32   63408.86       129219.61        46085.25  California
33        NaN       103057.49       214634.81     Florida
34   46426.07             NaN       210797.67  California
35   46014.02        85047.44       205517.64    New York
36   28663.76       127056.21       201126.82     Florida
37   44069.95        51283.14       197029.42  California
38   20229.59        65947.93       185265.10    New York
39   38558.51        82982.09             NaN  California